class EventsRepository:
    default_events_v2 = [
        {'id': 'dancing', 'emoji_number': '377', 'en': 'Dancing', 'ru': 'Танцы'},
        {'id': 'alcohol', 'emoji_number': '737', 'en': 'Alcohol', 'ru': 'Алкоголь'},
        {'id': 'allergy', 'emoji_number': '53', 'en': 'Allergy', 'ru': 'Аллергия'},
        {'id': 'bath', 'emoji_number': '433', 'en': 'Bath', 'ru': 'Ванна'},
        {'id': 'bicycle', 'emoji_number': '409', 'en': 'Bicycle', 'ru': 'Велосипед'},
        {'id': 'breakfast', 'emoji_number': '684', 'en': 'Breakfast', 'ru': 'Завтрак'},
        {'id': 'bustle', 'emoji_number': '76', 'en': 'Bustle', 'ru': 'Суета'},
        {'id': 'cleaning', 'emoji_number': '1287', 'en': 'Cleaning', 'ru': 'Уборка'},
        {'id': 'club', 'emoji_number': '378', 'en': 'Club', 'ru': 'Клуб'},
        {'id': 'cold', 'emoji_number': '961', 'en': 'Cold', 'ru': 'Холодная погода'},
        {'id': 'communication', 'emoji_number': '472', 'en': 'Communication', 'ru': 'Общение'},
        {'id': 'dancing', 'emoji_number': '377', 'en': 'Dancing', 'ru': 'Танцы'},
        {'id': 'date', 'emoji_number': '439', 'en': 'Date', 'ru': 'Свидание'},
        {'id': 'diet_food', 'emoji_number': '653', 'en': 'Diet food', 'ru': 'Диетическая еда'},
        {'id': 'dinner', 'emoji_number': '686', 'en': 'Dinner', 'ru': 'Ужин'},
        {'id': 'energy_drink', 'emoji_number': '960', 'en': 'Energy drink', 'ru': 'Энергетик'},
        {'id': 'family', 'emoji_number': '447', 'en': 'Family', 'ru': 'Семья'},
        {'id': 'fast_food', 'emoji_number': '673', 'en': 'Fast Food', 'ru': 'Фастфуд'},
        {'id': 'fatty_food', 'emoji_number': '672', 'en': 'Fatty food', 'ru': 'Жирная еда'},
        {'id': 'fiesta', 'emoji_number': '151', 'en': 'Siesta', 'ru': 'Дневной сон'},
        {'id': 'football', 'emoji_number': '995', 'en': 'Football', 'ru': 'Футбол'},
        {'id': 'fresh_air', 'emoji_number': '953', 'en': 'Fresh air', 'ru': 'Свежий воздух'},
        {'id': 'fruit', 'emoji_number': '634', 'en': 'Fruit', 'ru': 'Фрукты'},
        {'id': 'glass_of_water', 'emoji_number': '966', 'en': 'Glass of water', 'ru': 'Стакан воды'},
        {'id': 'good_weather', 'emoji_number': '836', 'en': 'Good weather', 'ru': 'Хорошая погода'},
        {'id': 'guests', 'emoji_number': '155', 'en': 'Guests', 'ru': 'Гости'},
        {'id': 'gym', 'emoji_number': '406', 'en': 'Gym', 'ru': 'Тренажерны зал'},
        {'id': 'gymnastic', 'emoji_number': '415', 'en': 'Gymnastic', 'ru': 'Гимнастика'},
        {'id': 'had_a_bite', 'emoji_number': '680', 'en': 'Had a bite', 'ru': 'Перекусил'},
        {'id': 'hot', 'emoji_number': '933', 'en': 'Hot', 'ru': 'Жарко'},
        {'id': 'insomnia', 'emoji_number': '196', 'en': 'Insomnia', 'ru': 'Бессоница'},
        {'id': 'jog', 'emoji_number': '375', 'en': 'Jog', 'ru': 'Пробежка'},
        {'id': 'laziness', 'emoji_number': '36', 'en': 'Laziness', 'ru': 'Лень'},
        {'id': 'light_food', 'emoji_number': '689', 'en': 'Light food', 'ru': 'Легкая еда'},
        {'id': 'lunch', 'emoji_number': '685', 'en': 'Lunch', 'ru': 'Обед'},
        {'id': 'massage', 'emoji_number': '352', 'en': 'Massage', 'ru': 'Массаж'},
        {'id': 'meditation', 'emoji_number': '430', 'en': 'Meditation', 'ru': 'Медитация'},
        {'id': 'meeting', 'emoji_number': '181', 'en': 'Meeting', 'ru': 'Встреча'},
        {'id': 'meeting_with_friends', 'emoji_number': '474', 'en': 'Meeting with friends', 'ru': 'Встреча с друзьями'},
        {'id': 'messenger', 'emoji_number': '1186', 'en': 'Messenger', 'ru': 'Мессенджер'},
        {'id': 'movie', 'emoji_number': '1143', 'en': 'Movie', 'ru': 'Фильм'},
        {'id': 'news', 'emoji_number': '1171', 'en': 'News', 'ru': 'Новости'},
        {'id': 'nightmare', 'emoji_number': '81', 'en': 'Nightmare', 'ru': 'Страшный сон'},
        {'id': 'painting', 'emoji_number': '1203', 'en': 'Painting', 'ru': 'Рисование'},
        {'id': 'panic_attack', 'emoji_number': '74', 'en': 'Panic attack', 'ru': 'Паническая атака'},
        {'id': 'party', 'emoji_number': '975', 'en': 'Party', 'ru': 'Тусовка'},
        {'id': 'phone', 'emoji_number': '1124', 'en': 'Phone', 'ru': 'Телефон'},
        {'id': 'prayer', 'emoji_number': '363', 'en': 'Prayer', 'ru': 'Молитва'},
        {'id': 'procrastination', 'emoji_number': '41', 'en': 'Procrastination', 'ru': 'Прокрастинация'},
        {'id': 'psychiatrist', 'emoji_number': '1033', 'en': 'Psychiatrist', 'ru': 'Психиатр'},
        {'id': 'psychologist', 'emoji_number': '247', 'en': 'Psychologist', 'ru': 'Психолог'},
        {'id': 'quarrels', 'emoji_number': '83', 'en': 'Quarrels', 'ru': 'Ссоры'},
        {'id': 'rain', 'emoji_number': '948', 'en': 'Rain', 'ru': 'Дождь'},
        {'id': 'road', 'emoji_number': '830', 'en': 'Road', 'ru': 'Дорога'},
        {'id': 'self_care', 'emoji_number': '1027', 'en': 'Self care', 'ru': 'Уход за собой'},
        {'id': 'shopping', 'emoji_number': '1075', 'en': 'Shopping', 'ru': 'Шоппинг'},
        {'id': 'shower', 'emoji_number': '1281', 'en': 'Shower', 'ru': 'Душ'},
        {'id': 'sigarettes', 'emoji_number': '1296', 'en': 'Sigarettes', 'ru': 'Сигареты'},
        {'id': 'sleepiness', 'emoji_number': '88', 'en': 'Sleepiness', 'ru': 'Сонливость'},
        {'id': 'snow', 'emoji_number': '949', 'en': 'Snow', 'ru': 'Снег'},
        {'id': 'social_media', 'emoji_number': '1125', 'en': 'Social media', 'ru': 'Социальные сети'},
        {'id': 'study', 'emoji_number': '1161', 'en': 'Study', 'ru': 'Учеба'},
        {'id': 'swimming_pool', 'emoji_number': '402', 'en': 'Swimming pool', 'ru': 'Бассейн'},
        {'id': 'tea', 'emoji_number': '733', 'en': 'Tea', 'ru': 'Чай'},
        {'id': 'tik_tok', 'emoji_number': '1125', 'en': 'Tik Tok', 'ru': 'Тик Ток'},
        {'id': 'tv_series', 'emoji_number': '1151', 'en': 'TV series', 'ru': 'Сериал'},
        {'id': 'vegetables', 'emoji_number': '652', 'en': 'Vegetables', 'ru': 'Овощи'},
        {'id': 'warm_up', 'emoji_number': '416', 'en': 'Warm-up', 'ru': 'Зарядка'},
        {'id': 'went_to_bed_early', 'emoji_number': '47', 'en': 'Went to bed early', 'ru': 'Рано лег'},
        {'id': 'went_to_bed_late', 'emoji_number': '47', 'en': 'Went to bed late', 'ru': 'Поздно лег'},
        {'id': 'woke_up_early', 'emoji_number': '46', 'en': 'Woke up early', 'ru': 'Рано проснулся'},
        {'id': 'workout', 'emoji_number': '376', 'en': 'Workout', 'ru': 'Тренировка'},
        {'id': 'yoga', 'emoji_number': '430', 'en': 'Yoga', 'ru': 'Йога'},
        {'id': 'youtube', 'emoji_number': '1147', 'en': 'Youtube', 'ru': 'Ютьюб'}
    ]

    default_events_excel = [
        {'id': 'sweet', 'emoji_number': '', 'ru': 'Сладкое', 'en': 'Sweet', 'ru_tag': 'Шоколад, конфеты, ',
         'en_tag': 'Chocolate, sweets, candies'},
        {'id': 'good_food', 'emoji_number': '', 'ru': 'Хорошая еда', 'en': 'Good food',
         'ru_tag': 'Свежая еда, вкусная еда', 'en_tag': 'Delicious food'},
        {'id': 'bad_food', 'emoji_number': '', 'ru': 'Плохая еда', 'en': 'Bad food', 'ru_tag': '', 'en_tag': ''},
        {'id': 'diet_food', 'emoji_number': '653', 'ru': 'Диетическая еда', 'en': 'Diet food', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'fatty_food', 'emoji_number': '672', 'ru': 'Жирная еда', 'en': 'Fatty food', 'ru_tag': '', 'en_tag': ''},
        {'id': 'light_food', 'emoji_number': '689', 'ru': 'Легкая еда', 'en': 'Light food', 'ru_tag': 'Салат',
         'en_tag': 'Salad'},
        {'id': 'had_a_bite', 'emoji_number': '680', 'ru': 'Перекусил', 'en': 'Had a bite',
         'ru_tag': 'Бутерброд, сэндвич, быстро поел', 'en_tag': 'Sandwich, ate quickly, had a snack'},
        {'id': 'fast_food', 'emoji_number': '673', 'ru': 'Фастфуд', 'en': 'Fast Food',
         'ru_tag': 'Гамбургер, Чизбургер, картошка фри, шаурма, донер, шаверма, беляш, картофель фри, макдональдс, бургер кинг, кфс',
         'en_tag': "Hamburger, cheeseburger, chips, shawarma, doner, belyash, chips, McDonald's, Burger King, KFC, JunkFood"},
        {'id': 'lunch', 'emoji_number': '685', 'ru': 'Обед', 'en': 'Lunch', 'ru_tag': '', 'en_tag': ''},
        {'id': 'breakfast', 'emoji_number': '684', 'ru': 'Завтрак', 'en': 'Breakfast', 'ru_tag': '', 'en_tag': ''},
        {'id': 'dinner', 'emoji_number': '686', 'ru': 'Ужин', 'en': 'Dinner', 'ru_tag': '', 'en_tag': ''},
        {'id': 'fruit', 'emoji_number': '634', 'ru': 'Фрукты', 'en': 'Fruit', 'ru_tag': '', 'en_tag': ''},
        {'id': 'vegetables', 'emoji_number': '652', 'ru': 'Овощи', 'en': 'Vegetables', 'ru_tag': '', 'en_tag': ''},
        {'id': 'alcohol', 'emoji_number': '737', 'ru': 'Алкоголь', 'en': 'Alcohol',
         'ru_tag': 'Пил, выпил, выпивал, накатил, пиво, вино, водка, напился, коньяк, виски, портвейн, нажрался, бухал, набухался',
         'en_tag': 'Drank, beer, wine, vodka, cognac, whiskey, port wine, got drunk, drank, swelled'},
        {'id': 'coffee', 'emoji_number': '', 'ru': 'Кофе', 'en': 'Coffee', 'ru_tag': 'Старбакс', 'en_tag': 'Starbucks'},
        {'id': 'glass_of_water', 'emoji_number': '966', 'ru': 'Стакан воды', 'en': 'Glass of water',
         'ru_tag': 'Выпил воду, стакан воды, ', 'en_tag': 'Drank water, glass of water'},
        {'id': 'tea', 'emoji_number': '733', 'ru': 'Чай', 'en': 'Tea', 'ru_tag': '', 'en_tag': ''},
        {'id': 'energy_drink', 'emoji_number': '960', 'ru': 'Энергетик', 'en': 'Energy drink', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'cooking', 'emoji_number': '', 'ru': 'Готовка', 'en': 'Cooking', 'ru_tag': 'Приготовл, готовил, ',
         'en_tag': 'Cooked, cooking'},
        {'id': 'games', 'emoji_number': '', 'ru': 'Видеоигры', 'en': 'Video games',
         'ru_tag': 'Дота, плойка, плейстейшин, иксбокс, играл, поиграл, Комьюерные игры, тащил мид',
         'en_tag': 'Dota, Play Station, Xbox, '},
        {'id': 'work', 'emoji_number': '', 'ru': 'Работа', 'en': 'Work', 'ru_tag': 'Поработал, работать, дело, труд',
         'en_tag': 'Worked, work, business, labour'},
        {'id': 'movie', 'emoji_number': '1143', 'ru': 'Фильм', 'en': 'Movie', 'ru_tag': 'кино',
         'en_tag': 'Cinema/movie'},
        {'id': 'music', 'emoji_number': '', 'ru': 'Музыка', 'en': 'Music', 'ru_tag': 'Послушал',
         'en_tag': 'Listened to music'},
        {'id': 'cleaning', 'emoji_number': '1287', 'ru': 'Уборка', 'en': 'Cleaning',
         'ru_tag': 'Убирался, убрался, чисто, чистота', 'en_tag': 'Cleaning, cleaned, clean, cleanliness'},
        {'id': 'tik_tok', 'emoji_number': '1125', 'ru': 'Тик Ток', 'en': 'Tik Tok', 'ru_tag': '', 'en_tag': ''},
        {'id': 'youtube', 'emoji_number': '1147', 'ru': 'Ютьюб', 'en': 'Youtube', 'ru_tag': '', 'en_tag': ''},
        {'id': 'tv_series', 'emoji_number': '1151', 'ru': 'Сериал', 'en': 'TV series', 'ru_tag': '', 'en_tag': ''},
        {'id': 'social_media', 'emoji_number': '1125', 'ru': 'Социальные сети', 'en': 'Social media',
         'ru_tag': 'Фейсбук, Вконтакте, вк, одноклассники, сидел в соц сетях, соц сети,  ',
         'en_tag': 'Facebook, Vk, vkontakte, odnoklasniki, surf the Internet/media'},
        {'id': 'study', 'emoji_number': '1161', 'ru': 'Учеба', 'en': 'Study', 'ru_tag': 'Обучение, учиться, учусь,',
         'en_tag': 'Study, studying, education'},
        {'id': 'shower', 'emoji_number': '1281', 'ru': 'Душ', 'en': 'Shower', 'ru_tag': '', 'en_tag': ''},
        {'id': 'bicycle', 'emoji_number': '409', 'ru': 'Велосипед', 'en': 'Bicycle', 'ru_tag': '', 'en_tag': ''},
        {'id': 'bath', 'emoji_number': '433', 'ru': 'Ванна', 'en': 'Bath', 'ru_tag': '', 'en_tag': ''},
        {'id': 'massage', 'emoji_number': '352', 'ru': 'Массаж', 'en': 'Massage', 'ru_tag': '', 'en_tag': ''},
        {'id': 'shopping', 'emoji_number': '1075', 'ru': 'Шоппинг', 'en': 'Shopping', 'ru_tag': 'Покупки, ',
         'en_tag': 'Purchases'},
        {'id': 'road', 'emoji_number': '830', 'ru': 'Дорога', 'en': 'Road', 'ru_tag': '', 'en_tag': ''},
        {'id': 'sigarettes', 'emoji_number': '1296', 'ru': 'Сигареты', 'en': 'Sigarettes', 'ru_tag': 'Курение, никотин',
         'en_tag': 'Smoking, nicotine'},
        {'id': 'self_care', 'emoji_number': '1027', 'ru': 'Уход за собой', 'en': 'Self care', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'meditation', 'emoji_number': '430', 'ru': 'Медитация', 'en': 'Meditation', 'ru_tag': '', 'en_tag': ''},
        {'id': 'swimming_pool', 'emoji_number': '402', 'ru': 'Бассейн', 'en': 'Swimming pool', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'news', 'emoji_number': '1171', 'ru': 'Новости', 'en': 'News', 'ru_tag': '', 'en_tag': ''},
        {'id': 'phone', 'emoji_number': '1124', 'ru': 'Телефон', 'en': 'Phone', 'ru_tag': '', 'en_tag': ''},
        {'id': 'prayer', 'emoji_number': '363', 'ru': 'Молитва', 'en': 'Prayer', 'ru_tag': '', 'en_tag': ''},
        {'id': 'painting', 'emoji_number': '1203', 'ru': 'Рисование', 'en': 'Painting', 'ru_tag': '', 'en_tag': ''},
        {'id': 'tour', 'emoji_number': '', 'ru': 'Прогулка', 'en': 'Promenade',
         'ru_tag': 'Погулял, прогулялся, прошелся, шел', 'en_tag': 'Walked, had a walk'},
        {'id': 'relax', 'emoji_number': '', 'ru': 'Отдых', 'en': 'Relax', 'ru_tag': 'Отднохнул, передохнул, чилил',
         'en_tag': 'Relaxed, took a break, chilled'},
        {'id': 'fresh_air', 'emoji_number': '953', 'ru': 'Свежий воздух', 'en': 'Fresh air',
         'ru_tag': 'Вышел на улицу, воздух, улица', 'en_tag': 'Went outside, air, street'},
        {'id': 'conflict', 'emoji_number': '', 'ru': 'Конфликт', 'en': 'Conflict', 'ru_tag': '', 'en_tag': ''},
        {'id': 'meeting_with_friends', 'emoji_number': '474', 'ru': 'Встреча с друзьями', 'en': 'Meeting with friends',
         'ru_tag': '', 'en_tag': ''},
        {'id': 'messenger', 'emoji_number': '1186', 'ru': 'Мессенджер', 'en': 'Messenger',
         'ru_tag': 'Телеграм, Вотсап, вайбер', 'en_tag': 'Telegram, WhatsApp, Viber'},
        {'id': 'communication', 'emoji_number': '472', 'ru': 'Общение', 'en': 'Communication', 'ru_tag': 'Беседа',
         'en_tag': 'Chat, conversation'},
        {'id': 'psychologist', 'emoji_number': '247', 'ru': 'Психолог', 'en': 'Psychologist', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'family', 'emoji_number': '447', 'ru': 'Семья', 'en': 'Family', 'ru_tag': '', 'en_tag': ''},
        {'id': 'date', 'emoji_number': '439', 'ru': 'Свидание', 'en': 'Date', 'ru_tag': '', 'en_tag': ''},
        {'id': 'guests', 'emoji_number': '155', 'ru': 'Гости', 'en': 'Guests', 'ru_tag': '', 'en_tag': ''},
        {'id': 'psychiatrist', 'emoji_number': '1033', 'ru': 'Психиатр', 'en': 'Psychiatrist', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'party', 'emoji_number': '975', 'ru': 'Тусовка', 'en': 'Party', 'ru_tag': '', 'en_tag': ''},
        {'id': 'club', 'emoji_number': '378', 'ru': 'Клуб', 'en': 'Club', 'ru_tag': '', 'en_tag': ''},
        {'id': 'quarrels', 'emoji_number': '83', 'ru': 'Ссоры', 'en': 'Quarrels',
         'ru_tag': 'Ссора, посорился, посрался, посрались, посорились, посорилась',
         'en_tag': 'Quarrel, had an argument, argued, had a fight, quarrelled'},
        {'id': 'meeting', 'emoji_number': '181', 'ru': 'Встреча', 'en': 'Meeting', 'ru_tag': '', 'en_tag': ''},
        {'id': 'good_dream', 'emoji_number': '', 'ru': 'Хороший сон', 'en': 'Good dream', 'ru_tag': '', 'en_tag': ''},
        {'id': 'nightmare', 'emoji_number': '81', 'ru': 'Страшный сон', 'en': 'Nightmare', 'ru_tag': '', 'en_tag': ''},
        {'id': 'bad_dream', 'emoji_number': '', 'ru': 'Плохой сон', 'en': 'Bad dream', 'ru_tag': '', 'en_tag': ''},
        {'id': 'woke_up_late', 'emoji_number': '', 'ru': 'Поздно проснулся', 'en': 'Woke up late', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'went_to_bed_late', 'emoji_number': '47', 'ru': 'Поздно лег', 'en': 'Went to bed late', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'woke_up_early', 'emoji_number': '46', 'ru': 'Рано проснулся', 'en': 'Woke up early', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'went_to_bed_early', 'emoji_number': '47', 'ru': 'Рано лег', 'en': 'Went to bed early', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'insomnia', 'emoji_number': '196', 'ru': 'Бессоница', 'en': 'Insomnia', 'ru_tag': 'Не выспался',
         'en_tag': "Didn't sleep enough"},
        {'id': 'fiesta', 'emoji_number': '151', 'ru': 'Дневной сон', 'en': 'Fiesta', 'ru_tag': '', 'en_tag': 'nap'},
        {'id': 'sleepiness', 'emoji_number': '88', 'ru': 'Сонливость', 'en': 'Sleepiness', 'ru_tag': 'Не выспался',
         'en_tag': "Didn't sleep enough"},
        {'id': 'good_weather', 'emoji_number': '836', 'ru': 'Хорошая погода', 'en': 'Good weather',
         'ru_tag': 'Ясно, солнечно', 'en_tag': 'Clear, sunny'},
        {'id': 'rain', 'emoji_number': '948', 'ru': 'Дождь', 'en': 'Rain', 'ru_tag': '', 'en_tag': ''},
        {'id': 'cold', 'emoji_number': '961', 'ru': 'Холодная погода', 'en': 'Cold', 'ru_tag': '', 'en_tag': ''},
        {'id': 'snow', 'emoji_number': '949', 'ru': 'Снег', 'en': 'Snow', 'ru_tag': '', 'en_tag': ''},
        {'id': '', 'emoji_number': '', 'ru': '', 'en': '', 'ru_tag': '', 'en_tag': ''},
        {'id': 'hot', 'emoji_number': '933', 'ru': 'Жарко', 'en': 'Hot', 'ru_tag': '', 'en_tag': 'boiling'},
        {'id': '', 'emoji_number': '', 'ru': '', 'en': '', 'ru_tag': '', 'en_tag': ''},
        {'id': '', 'emoji_number': '', 'ru': '', 'en': '', 'ru_tag': 'Mental states', 'en_tag': ''},
        {'id': 'lemon', 'emoji_number': '', 'ru': 'Выжат как лимон', 'en': 'Wiped out', 'ru_tag': '', 'en_tag': ''},
        {'id': 'meditation', 'emoji_number': '', 'ru': 'Медитация', 'en': 'Meditation', 'ru_tag': '', 'en_tag': ''},
        {'id': 'migraine', 'emoji_number': '', 'ru': 'Мигрень', 'en': 'Migraine',
         'ru_tag': 'Болит голова, головная боль,', 'en_tag': 'Headache'},
        {'id': 'sick', 'emoji_number': '', 'ru': 'Болезнь', 'en': 'Sickness', 'ru_tag': '', 'en_tag': ''},
        {'id': 'procrastination', 'emoji_number': '41', 'ru': 'Прокрастенация', 'en': 'Procrastination', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'allergy', 'emoji_number': '53', 'ru': 'Аллергия', 'en': 'Allergy', 'ru_tag': '', 'en_tag': ''},
        {'id': 'bustle', 'emoji_number': '76', 'ru': 'Суета', 'en': 'Bustle', 'ru_tag': '', 'en_tag': ''},
        {'id': 'laziness', 'emoji_number': '36', 'ru': 'Лень', 'en': 'Laziness', 'ru_tag': 'Лениво, ленюсь',
         'en_tag': 'Lazy'},
        {'id': 'panic_attack', 'emoji_number': '74', 'ru': 'Паническая атака', 'en': 'Panic attack', 'ru_tag': '',
         'en_tag': ''},
        {'id': 'sport', 'emoji_number': '', 'ru': 'Спорт', 'en': 'Sport', 'ru_tag': 'Тенис', 'en_tag': 'Tennis'},
        {'id': 'jog', 'emoji_number': '375', 'ru': 'Пробежка', 'en': 'Jog', 'ru_tag': '', 'en_tag': ''},
        {'id': 'gym', 'emoji_number': '406', 'ru': 'Тренажерны зал', 'en': 'Gym', 'ru_tag': '', 'en_tag': ''},
        {'id': 'yoga', 'emoji_number': '430', 'ru': 'Йога', 'en': 'Yoga', 'ru_tag': '', 'en_tag': ''},
        {'id': 'gymnastic', 'emoji_number': '415', 'ru': 'Гимнастика', 'en': 'Gymnastic', 'ru_tag': '', 'en_tag': ''},
        {'id': 'dancing', 'emoji_number': '377', 'ru': 'Танцы', 'en': 'Dancing', 'ru_tag': '', 'en_tag': ''},
        {'id': 'workout', 'emoji_number': '376', 'ru': 'Тренировка', 'en': 'Workout', 'ru_tag': '', 'en_tag': ''},
        {'id': 'warm_up', 'emoji_number': '416', 'ru': 'Зарядка', 'en': 'Warm-up', 'ru_tag': '', 'en_tag': ''},
        {'id': 'football', 'emoji_number': '995', 'ru': 'Футбол', 'en': 'Football', 'ru_tag': '', 'en_tag': ''},
    ]
